# Generated by Django 3.1.3 on 2024-03-09 20:18

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25, unique=True)),
                ('project_detail', models.CharField(max_length=30)),
                ('project_image', versatileimagefield.fields.VersatileImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_deadline', models.DateField()),
                ('student_image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='profile')),
                ('student_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestone.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=25, unique=True)),
                ('task_description', models.CharField(max_length=150)),
                ('task_deadline', models.DateField()),
                ('task_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestone.student')),
            ],
        ),
    ]
