# Generated by Django 3.1.3 on 2024-03-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_detail',
            field=models.CharField(max_length=150),
        ),
    ]
